# You can add custom log sources here if you use sigma rules that reference these custom log sources.
# For the list of built-in log sources, see: https://github.com/SigmaHQ/sigma/blob/master/tools/config/thor.yml
logsources: